services:
  web:
    build: .
    ports:
      - 8080:80
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: 'USER_DB'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    # volumes:
    #     - ./db/init.sql:/docker-entrypoint-initdb.d/A_init.sql
